version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - SECRET_KEY=change-me
      - DATABASE_URL=sqlite+sqlite:///./app.db
    volumes:
      - ./:/app


