"""add

Revision ID: 22e747f05aae
Revises: 5eb2fa1eabc0
Create Date: 2025-09-27 02:29:21.342568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e747f05aae'
down_revision = '5eb2fa1eabc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
